### ISSUE TITLE
Judgement Debuff

### ISSUE THREAD

**Issue by vamman311** [laytya/Kui-Namaplates#7]
When judging a seal on an enemy the debuff for the judgement is properly displayed on the nameplates however; the debuff will not update its time upon a successful melee hit.

After the issues occurs the judgement debuff will also remain on the nameplate with a time of 0 until you deselect the target

**Comment by laytya** [comment]
Its very difficult to catch this refresh by melee hit. 

about 0 timers - i fixed it already - wait in next update

**Comment by Xirmak** [comment]
Srill not fixed. The wisdom buff for example ticks down 10 seconds and blinks at 0. it will remain until you untarget it goes away but the buff was refreshed with each melee hit. not sure if it helps or if its a difference in coding, pfui/shauplates nameplates are able to accomplish the refresh on melee hit. might be something to look in how that finds the data or how it is written
